/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
public class BuddyResultState implements org.apache.thrift.TEnum {

  public static final BuddyResultState ACCEPTED = new BuddyResultState(1);
  public static final BuddyResultState SUCCEEDED = new BuddyResultState(2);
  public static final BuddyResultState FAILED = new BuddyResultState(3);
  public static final BuddyResultState CANCELLED = new BuddyResultState(4);
  public static final BuddyResultState NOTIFY_FAILED = new BuddyResultState(5);
  public static final BuddyResultState STORING = new BuddyResultState(11);
  public static final BuddyResultState UPLOADING = new BuddyResultState(21);
  public static final BuddyResultState NOTIFYING = new BuddyResultState(31);
  public static final BuddyResultState REMOVING_SUBSCRIPTION = new BuddyResultState(41);
  public static final BuddyResultState UNREGISTERING_ACCOUNT = new BuddyResultState(42);
  public static final BuddyResultState NOTIFYING_LEAVE_CHAT = new BuddyResultState(43);

  private final int value;

  private BuddyResultState(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static BuddyResultState findByValue(int value) { 
    switch (value) {
      case 1:
        return ACCEPTED;
      case 2:
        return SUCCEEDED;
      case 3:
        return FAILED;
      case 4:
        return CANCELLED;
      case 5:
        return NOTIFY_FAILED;
      case 11:
        return STORING;
      case 21:
        return UPLOADING;
      case 31:
        return NOTIFYING;
      case 41:
        return REMOVING_SUBSCRIPTION;
      case 42:
        return UNREGISTERING_ACCOUNT;
      case 43:
        return NOTIFYING_LEAVE_CHAT;
      default:
        return null;
    }
  }
}
