/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;

using Thrift.Protocols;
using Thrift.Protocols.Entities;
using Thrift.Protocols.Utilities;
using Thrift.Transports;
using Thrift.Transports.Client;
using Thrift.Transports.Server;



public partial class ApprovedChannelInfo : TBase
{
  private ChannelInfo _channelInfo;
  private long _approvedAt;

  public ChannelInfo ChannelInfo
  {
    get
    {
      return _channelInfo;
    }
    set
    {
      __isset.channelInfo = true;
      this._channelInfo = value;
    }
  }

  public long ApprovedAt
  {
    get
    {
      return _approvedAt;
    }
    set
    {
      __isset.approvedAt = true;
      this._approvedAt = value;
    }
  }


  public Isset __isset;
  public struct Isset
  {
    public bool channelInfo;
    public bool approvedAt;
  }

  public ApprovedChannelInfo()
  {
  }

  public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct)
            {
              ChannelInfo = new ChannelInfo();
              await ChannelInfo.ReadAsync(iprot, cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.I64)
            {
              ApprovedAt = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var struc = new TStruct("ApprovedChannelInfo");
      await oprot.WriteStructBeginAsync(struc, cancellationToken);
      var field = new TField();
      if (ChannelInfo != null && __isset.channelInfo)
      {
        field.Name = "channelInfo";
        field.Type = TType.Struct;
        field.ID = 1;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await ChannelInfo.WriteAsync(oprot, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if (__isset.approvedAt)
      {
        field.Name = "approvedAt";
        field.Type = TType.I64;
        field.ID = 2;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteI64Async(ApprovedAt, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString()
  {
    var sb = new StringBuilder("ApprovedChannelInfo(");
    bool __first = true;
    if (ChannelInfo != null && __isset.channelInfo)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("ChannelInfo: ");
      sb.Append(ChannelInfo== null ? "<null>" : ChannelInfo.ToString());
    }
    if (__isset.approvedAt)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("ApprovedAt: ");
      sb.Append(ApprovedAt);
    }
    sb.Append(")");
    return sb.ToString();
  }
}

