/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum GroupAttribute
{
  NAME = 1,
  PICTURE_STATUS = 2,
  ALL = 255,
  PREVENTED_JOIN_BY_TICKET = 4,
  NOTIFICATION_SETTING = 8,
}
