/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
library line.src.chat_room_announcement_type;

class ChatRoomAnnouncementType {
  static const int MESSAGE = 0;
  static const int NOTE = 1;

  static final Set<int> VALID_VALUES = new Set.from([
    MESSAGE
    , NOTE
  ]);
  static final Map<int, String> VALUES_TO_NAMES = {
    MESSAGE: 'MESSAGE'
    , NOTE: 'NOTE'
  };
}
