/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
library line.src.notification_type;

class NotificationType {
  static const int APPLE_APNS = 1;
  static const int GOOGLE_C2DM = 2;
  static const int NHN_NNI = 3;
  static const int SKT_AOM = 4;
  static const int MS_MPNS = 5;
  static const int RIM_BIS = 6;
  static const int GOOGLE_GCM = 7;
  static const int NOKIA_NNAPI = 8;
  static const int TIZEN = 9;
  static const int LINE_BOT = 17;
  static const int LINE_WAP = 18;
  static const int APPLE_APNS_VOIP = 19;
  static const int MS_WNS = 20;
  static const int GOOGLE_FCM = 21;

  static final Set<int> VALID_VALUES = new Set.from([
    APPLE_APNS
    , GOOGLE_C2DM
    , NHN_NNI
    , SKT_AOM
    , MS_MPNS
    , RIM_BIS
    , GOOGLE_GCM
    , NOKIA_NNAPI
    , TIZEN
    , LINE_BOT
    , LINE_WAP
    , APPLE_APNS_VOIP
    , MS_WNS
    , GOOGLE_FCM
  ]);
  static final Map<int, String> VALUES_TO_NAMES = {
    APPLE_APNS: 'APPLE_APNS'
    , GOOGLE_C2DM: 'GOOGLE_C2DM'
    , NHN_NNI: 'NHN_NNI'
    , SKT_AOM: 'SKT_AOM'
    , MS_MPNS: 'MS_MPNS'
    , RIM_BIS: 'RIM_BIS'
    , GOOGLE_GCM: 'GOOGLE_GCM'
    , NOKIA_NNAPI: 'NOKIA_NNAPI'
    , TIZEN: 'TIZEN'
    , LINE_BOT: 'LINE_BOT'
    , LINE_WAP: 'LINE_WAP'
    , APPLE_APNS_VOIP: 'APPLE_APNS_VOIP'
    , MS_WNS: 'MS_WNS'
    , GOOGLE_FCM: 'GOOGLE_FCM'
  };
}
