/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class CreateSquareChatRequest : TBase
{
  private int _reqSeq;
  private SquareChat _squareChat;
  private List<string> _squareMemberMids;

  public int ReqSeq
  {
    get
    {
      return _reqSeq;
    }
    set
    {
      __isset.reqSeq = true;
      this._reqSeq = value;
    }
  }

  public SquareChat SquareChat
  {
    get
    {
      return _squareChat;
    }
    set
    {
      __isset.squareChat = true;
      this._squareChat = value;
    }
  }

  public List<string> SquareMemberMids
  {
    get
    {
      return _squareMemberMids;
    }
    set
    {
      __isset.squareMemberMids = true;
      this._squareMemberMids = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool reqSeq;
    public bool squareChat;
    public bool squareMemberMids;
  }

  public CreateSquareChatRequest() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              ReqSeq = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Struct) {
              SquareChat = new SquareChat();
              SquareChat.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.List) {
              {
                SquareMemberMids = new List<string>();
                TList _list380 = iprot.ReadListBegin();
                for( int _i381 = 0; _i381 < _list380.Count; ++_i381)
                {
                  string _elem382;
                  _elem382 = iprot.ReadString();
                  SquareMemberMids.Add(_elem382);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("CreateSquareChatRequest");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.reqSeq) {
        field.Name = "reqSeq";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(ReqSeq);
        oprot.WriteFieldEnd();
      }
      if (SquareChat != null && __isset.squareChat) {
        field.Name = "squareChat";
        field.Type = TType.Struct;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        SquareChat.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (SquareMemberMids != null && __isset.squareMemberMids) {
        field.Name = "squareMemberMids";
        field.Type = TType.List;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.String, SquareMemberMids.Count));
          foreach (string _iter383 in SquareMemberMids)
          {
            oprot.WriteString(_iter383);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("CreateSquareChatRequest(");
    bool __first = true;
    if (__isset.reqSeq) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("ReqSeq: ");
      __sb.Append(ReqSeq);
    }
    if (SquareChat != null && __isset.squareChat) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("SquareChat: ");
      __sb.Append(SquareChat== null ? "<null>" : SquareChat.ToString());
    }
    if (SquareMemberMids != null && __isset.squareMemberMids) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("SquareMemberMids: ");
      __sb.Append(SquareMemberMids);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

