/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class SquareFeature : TBase
{
  private SquareFeatureControlState _controlState;
  private BooleanState _booleanValue;

  /// <summary>
  /// 
  /// <seealso cref="SquareFeatureControlState"/>
  /// </summary>
  public SquareFeatureControlState ControlState
  {
    get
    {
      return _controlState;
    }
    set
    {
      __isset.controlState = true;
      this._controlState = value;
    }
  }

  /// <summary>
  /// 
  /// <seealso cref="BooleanState"/>
  /// </summary>
  public BooleanState BooleanValue
  {
    get
    {
      return _booleanValue;
    }
    set
    {
      __isset.booleanValue = true;
      this._booleanValue = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool controlState;
    public bool booleanValue;
  }

  public SquareFeature() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              ControlState = (SquareFeatureControlState)iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              BooleanValue = (BooleanState)iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("SquareFeature");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.controlState) {
        field.Name = "controlState";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32((int)ControlState);
        oprot.WriteFieldEnd();
      }
      if (__isset.booleanValue) {
        field.Name = "booleanValue";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32((int)BooleanValue);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("SquareFeature(");
    bool __first = true;
    if (__isset.controlState) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("ControlState: ");
      __sb.Append(ControlState);
    }
    if (__isset.booleanValue) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("BooleanValue: ");
      __sb.Append(BooleanValue);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

