/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package 
{
import org.apache.thrift.Set;
import flash.utils.Dictionary;
  public class ContactType   {
    public static const MID:int = 0;
    public static const PHONE:int = 1;
    public static const EMAIL:int = 2;
    public static const USERID:int = 3;
    public static const PROXIMITY:int = 4;
    public static const GROUP:int = 5;
    public static const USER:int = 6;
    public static const QRCODE:int = 7;
    public static const PROMOTION_BOT:int = 8;
    public static const CONTACT_MESSAGE:int = 9;
    public static const FRIEND_REQUEST:int = 10;
    public static const REPAIR:int = 128;
    public static const FACEBOOK:int = 2305;
    public static const SINA:int = 2306;
    public static const RENREN:int = 2307;
    public static const FEIXIN:int = 2308;
    public static const BBM:int = 2309;
    public static const BEACON:int = 11;

    public static const VALID_VALUES:Set = new Set(MID, PHONE, EMAIL, USERID, PROXIMITY, GROUP, USER, QRCODE, PROMOTION_BOT, CONTACT_MESSAGE, FRIEND_REQUEST, REPAIR, FACEBOOK, SINA, RENREN, FEIXIN, BBM, BEACON);
    public static const VALUES_TO_NAMES:Dictionary = new Dictionary();
    {
      VALUES_TO_NAMES[MID] = "MID";
      VALUES_TO_NAMES[PHONE] = "PHONE";
      VALUES_TO_NAMES[EMAIL] = "EMAIL";
      VALUES_TO_NAMES[USERID] = "USERID";
      VALUES_TO_NAMES[PROXIMITY] = "PROXIMITY";
      VALUES_TO_NAMES[GROUP] = "GROUP";
      VALUES_TO_NAMES[USER] = "USER";
      VALUES_TO_NAMES[QRCODE] = "QRCODE";
      VALUES_TO_NAMES[PROMOTION_BOT] = "PROMOTION_BOT";
      VALUES_TO_NAMES[CONTACT_MESSAGE] = "CONTACT_MESSAGE";
      VALUES_TO_NAMES[FRIEND_REQUEST] = "FRIEND_REQUEST";
      VALUES_TO_NAMES[REPAIR] = "REPAIR";
      VALUES_TO_NAMES[FACEBOOK] = "FACEBOOK";
      VALUES_TO_NAMES[SINA] = "SINA";
      VALUES_TO_NAMES[RENREN] = "RENREN";
      VALUES_TO_NAMES[FEIXIN] = "FEIXIN";
      VALUES_TO_NAMES[BBM] = "BBM";
      VALUES_TO_NAMES[BEACON] = "BEACON";

    }
  }
}
