/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package 
{
import org.apache.thrift.Set;
import flash.utils.Dictionary;
  public class MessageRelationType   {
    public static const FORWARD:int = 0;
    public static const AUTO_REPLY:int = 1;
    public static const SUBORDINATE:int = 2;

    public static const VALID_VALUES:Set = new Set(FORWARD, AUTO_REPLY, SUBORDINATE);
    public static const VALUES_TO_NAMES:Dictionary = new Dictionary();
    {
      VALUES_TO_NAMES[FORWARD] = "FORWARD";
      VALUES_TO_NAMES[AUTO_REPLY] = "AUTO_REPLY";
      VALUES_TO_NAMES[SUBORDINATE] = "SUBORDINATE";

    }
  }
}
