/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package 
{
import org.apache.thrift.Set;
import flash.utils.Dictionary;
  public class PayloadType   {
    public static const PAYLOAD_BUY:int = 101;
    public static const PAYLOAD_CS:int = 111;
    public static const PAYLOAD_BONUS:int = 121;
    public static const PAYLOAD_EVENT:int = 131;

    public static const VALID_VALUES:Set = new Set(PAYLOAD_BUY, PAYLOAD_CS, PAYLOAD_BONUS, PAYLOAD_EVENT);
    public static const VALUES_TO_NAMES:Dictionary = new Dictionary();
    {
      VALUES_TO_NAMES[PAYLOAD_BUY] = "PAYLOAD_BUY";
      VALUES_TO_NAMES[PAYLOAD_CS] = "PAYLOAD_CS";
      VALUES_TO_NAMES[PAYLOAD_BONUS] = "PAYLOAD_BONUS";
      VALUES_TO_NAMES[PAYLOAD_EVENT] = "PAYLOAD_EVENT";

    }
  }
}
