/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package;

import org.apache.thrift.helper.*;
import haxe.io.Bytes;
import haxe.ds.IntMap;
import haxe.ds.StringMap;
import haxe.ds.ObjectMap;

#if flash
import flash.errors.ArgumentError;
#end

import org.apache.thrift.*;
import org.apache.thrift.meta_data.*;
import org.apache.thrift.protocol.*;


class SnsProfile implements TBase {
  
  static var STRUCT_DESC = { new TStruct("SnsProfile"); };
  static var SNS_USER_ID_FIELD_DESC = { new TField("snsUserId", TType.STRING, 1); };
  static var SNS_USER_NAME_FIELD_DESC = { new TField("snsUserName", TType.STRING, 2); };
  static var EMAIL_FIELD_DESC = { new TField("email", TType.STRING, 3); };
  static var THUMBNAIL_URL_FIELD_DESC = { new TField("thumbnailUrl", TType.STRING, 4); };

  @:isVar
  public var snsUserId(get,set) : String;
  @:isVar
  public var snsUserName(get,set) : String;
  @:isVar
  public var email(get,set) : String;
  @:isVar
  public var thumbnailUrl(get,set) : String;

  inline static var SNSUSERID_FIELD_ID : Int = 1;
  inline static var SNSUSERNAME_FIELD_ID : Int = 2;
  inline static var EMAIL_FIELD_ID : Int = 3;
  inline static var THUMBNAILURL_FIELD_ID : Int = 4;


  public function new() {
  }

  public function get_snsUserId() : String {
    return this.snsUserId;
  }

  public function set_snsUserId(snsUserId:String) : String {
    this.snsUserId = snsUserId;
    return this.snsUserId;
  }

  public function unsetSnsUserId() : Void {
    this.snsUserId = null;
  }

  // Returns true if field snsUserId is set (has been assigned a value) and false otherwise
  public function isSetSnsUserId() : Bool {
    return this.snsUserId != null;
  }

  public function get_snsUserName() : String {
    return this.snsUserName;
  }

  public function set_snsUserName(snsUserName:String) : String {
    this.snsUserName = snsUserName;
    return this.snsUserName;
  }

  public function unsetSnsUserName() : Void {
    this.snsUserName = null;
  }

  // Returns true if field snsUserName is set (has been assigned a value) and false otherwise
  public function isSetSnsUserName() : Bool {
    return this.snsUserName != null;
  }

  public function get_email() : String {
    return this.email;
  }

  public function set_email(email:String) : String {
    this.email = email;
    return this.email;
  }

  public function unsetEmail() : Void {
    this.email = null;
  }

  // Returns true if field email is set (has been assigned a value) and false otherwise
  public function isSetEmail() : Bool {
    return this.email != null;
  }

  public function get_thumbnailUrl() : String {
    return this.thumbnailUrl;
  }

  public function set_thumbnailUrl(thumbnailUrl:String) : String {
    this.thumbnailUrl = thumbnailUrl;
    return this.thumbnailUrl;
  }

  public function unsetThumbnailUrl() : Void {
    this.thumbnailUrl = null;
  }

  // Returns true if field thumbnailUrl is set (has been assigned a value) and false otherwise
  public function isSetThumbnailUrl() : Bool {
    return this.thumbnailUrl != null;
  }

  public function setFieldValue(fieldID : Int, value : Dynamic) : Void {
    switch (fieldID) {
    case SNSUSERID_FIELD_ID:
      if (value == null) {
        unsetSnsUserId();
      } else {
        this.snsUserId = value;
      }

    case SNSUSERNAME_FIELD_ID:
      if (value == null) {
        unsetSnsUserName();
      } else {
        this.snsUserName = value;
      }

    case EMAIL_FIELD_ID:
      if (value == null) {
        unsetEmail();
      } else {
        this.email = value;
      }

    case THUMBNAILURL_FIELD_ID:
      if (value == null) {
        unsetThumbnailUrl();
      } else {
        this.thumbnailUrl = value;
      }

    default:
      throw new ArgumentError("Field " + fieldID + " doesn't exist!");
    }
  }

  public function getFieldValue(fieldID : Int) : Dynamic {
    switch (fieldID) {
    case SNSUSERID_FIELD_ID:
      return this.snsUserId;
    case SNSUSERNAME_FIELD_ID:
      return this.snsUserName;
    case EMAIL_FIELD_ID:
      return this.email;
    case THUMBNAILURL_FIELD_ID:
      return this.thumbnailUrl;
    default:
      throw new ArgumentError("Field " + fieldID + " doesn't exist!");
    }
  }

  // Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise
  public function isSet(fieldID : Int) : Bool {
    switch (fieldID) {
    case SNSUSERID_FIELD_ID:
      return isSetSnsUserId();
    case SNSUSERNAME_FIELD_ID:
      return isSetSnsUserName();
    case EMAIL_FIELD_ID:
      return isSetEmail();
    case THUMBNAILURL_FIELD_ID:
      return isSetThumbnailUrl();
    default:
      throw new ArgumentError("Field " + fieldID + " doesn't exist!");
    }
  }

  public function read( iprot : TProtocol) : Void {
    iprot.IncrementRecursionDepth();
    try
    {
      var field : TField;
      iprot.readStructBegin();
      while (true)
      {
        field = iprot.readFieldBegin();
        if (field.type == TType.STOP) { 
          break;
        }
        switch (field.id)
        {
          case SNSUSERID_FIELD_ID:
            if (field.type == TType.STRING) {
              this.snsUserId = iprot.readString();
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
          case SNSUSERNAME_FIELD_ID:
            if (field.type == TType.STRING) {
              this.snsUserName = iprot.readString();
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
          case EMAIL_FIELD_ID:
            if (field.type == TType.STRING) {
              this.email = iprot.readString();
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
          case THUMBNAILURL_FIELD_ID:
            if (field.type == TType.STRING) {
              this.thumbnailUrl = iprot.readString();
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
          default:
            TProtocolUtil.skip(iprot, field.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      iprot.DecrementRecursionDepth();
    }
    catch(e:Dynamic)
    {
      iprot.DecrementRecursionDepth();
      throw e;
    }

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  public function write(oprot:TProtocol) : Void {
    validate();
    oprot.IncrementRecursionDepth();
    try
    {
      oprot.writeStructBegin(STRUCT_DESC);
      if (this.snsUserId != null) {
        oprot.writeFieldBegin(SNS_USER_ID_FIELD_DESC);
        oprot.writeString(this.snsUserId);
        oprot.writeFieldEnd();
      }
      if (this.snsUserName != null) {
        oprot.writeFieldBegin(SNS_USER_NAME_FIELD_DESC);
        oprot.writeString(this.snsUserName);
        oprot.writeFieldEnd();
      }
      if (this.email != null) {
        oprot.writeFieldBegin(EMAIL_FIELD_DESC);
        oprot.writeString(this.email);
        oprot.writeFieldEnd();
      }
      if (this.thumbnailUrl != null) {
        oprot.writeFieldBegin(THUMBNAIL_URL_FIELD_DESC);
        oprot.writeString(this.thumbnailUrl);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
      oprot.DecrementRecursionDepth();
    }
    catch(e:Dynamic)
    {
      oprot.DecrementRecursionDepth();
      throw e;
    }
  }

  public function toString() : String {
    var ret : String = "SnsProfile(";
    var first : Bool = true;

    ret += "snsUserId:";
    if (this.snsUserId == null) {
      ret += "null";
    } else {
      ret += this.snsUserId;
    }
    first = false;
    if (!first) ret +=  ", ";
    ret += "snsUserName:";
    if (this.snsUserName == null) {
      ret += "null";
    } else {
      ret += this.snsUserName;
    }
    first = false;
    if (!first) ret +=  ", ";
    ret += "email:";
    if (this.email == null) {
      ret += "null";
    } else {
      ret += this.email;
    }
    first = false;
    if (!first) ret +=  ", ";
    ret += "thumbnailUrl:";
    if (this.thumbnailUrl == null) {
      ret += "null";
    } else {
      ret += this.thumbnailUrl;
    }
    first = false;
    ret += ")";
    return ret;
  }

  public function validate() : Void {
    // check for required fields
    // check that fields of type enum have valid values
  }

}

