/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
public class NotificationQueueType implements org.apache.thrift.TEnum {

  public static final NotificationQueueType GLOBAL = new NotificationQueueType(1);
  public static final NotificationQueueType MESSAGE = new NotificationQueueType(2);
  public static final NotificationQueueType PRIMARY = new NotificationQueueType(3);

  private final int value;

  private NotificationQueueType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static NotificationQueueType findByValue(int value) { 
    switch (value) {
      case 1:
        return GLOBAL;
      case 2:
        return MESSAGE;
      case 3:
        return PRIMARY;
      default:
        return null;
    }
  }
}
