<?php
/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

final class SquareMembershipState
{
    const JOIN_REQUESTED = 1;

    const JOINED = 2;

    const REJECTED = 3;

    const LEFT = 4;

    const KICK_OUT = 5;

    const BANNED = 6;

    const DELETED = 7;

    static public $__names = array(
        1 => 'JOIN_REQUESTED',
        2 => 'JOINED',
        3 => 'REJECTED',
        4 => 'LEFT',
        5 => 'KICK_OUT',
        6 => 'BANNED',
        7 => 'DELETED',
    );
}

